config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get 'lock_user', to: 'users/sessions#lock_user'
    post 'unlock_user', to: 'users/sessions#unlock_user'
  end

  resources :business_clients, except: [:show, :destroy, :edit], path: 'clients', as: 'clients' do

    get :autocomplete, on: :collection

    resources :business_companies, path: 'companies', only:[:show, :update] do

      get :preferences, on: :member

      namespace 'bc' do
        resources :departments
        resources :branches
        resources :medical_clinics
      end

      resources :dashboard, only: [:index]
      resources :claimants
    end
  end

  root to: 'home#index'
  get 'dashboard', to: 'users/dashboard#index', as: :dashboard
  get '*unmatched_route', :to => 'home#routing_error'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :owner
      can :manage, :all
    elsif user.has_role? :client
      cannot :manage, [:business_clients]
      can [:update], BusinessClient, id: user.id
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true, optional: true

  validates :address, presence: true, length: {maximum: 255}
  validates :city, :state, presence: true, length: {maximum: 50}
  validates :zip, allow_blank: true, length: {maximum: 15}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :created_at_desc, -> { order('created_at DESC') }
  scope :created_at_asc, -> { order('created_at ASC') }
end

app/models/bc_task.rb
class BcTask < ApplicationRecord
  belongs_to :business_company
  belongs_to :task

  #before_save :custom_validation

  def name
    task.name
  end
end

app/models/body_part.rb
class BodyPart < ApplicationRecord
  scope :order_by_name, -> { order("name") }
end

app/models/branch.rb
class Branch < ApplicationRecord

  belongs_to :business_company
  # has_many :employees
  # has_many :medical_clinics

end

app/models/business_client.rb
class BusinessClient < User
  attr_accessor :name
  has_many :business_companies
  accepts_nested_attributes_for :business_companies

end

app/models/business_company.rb
class BusinessCompany < ApplicationRecord

  belongs_to :business_client
  has_many :employees
  has_many :branches
  has_many :departments
  has_many :medical_clinics
  has_many :bc_tasks
  has_many :payment_profiles, dependent: :destroy

  validates :name, presence: true, length: {maximum: 110}
  validates :phone, presence: true, length: {maximum: 18}, format: { with: /\A[+]{0,1}[\s\/\(\)\-\.\d]{10,15}\z/ }

  accepts_nested_attributes_for :branches, allow_destroy: true
  accepts_nested_attributes_for :departments, allow_destroy: true
  accepts_nested_attributes_for :payment_profiles, allow_destroy: true
  accepts_nested_attributes_for :bc_tasks, allow_destroy: true

  after_create :build_tasks

  include DateTimeParser
  include WcaAddressable

  scope :search_by_name, -> (keyword){ where("lower(name) like ? ", "%#{keyword.downcase}%") }

  WHO_TO_BILL = { 'Company': 1, 'Broker': 2, 'Insurance Company': 3 }
  PAYMENT_OPTIONS = { 'Auto-Pay with this Credit Card': 1, 'Email me monthly billing': 2 }

  def client
    business_client
  end

  def contact_person_email
    client.email
  end

  def contact_person_phone
    client.phone
  end

  def contact_person_name
    client.full_name
  end

  private

  def build_tasks
    Task.all.each{ |task| self.bc_tasks.create(task_id: task.id) }
  end

end

app/models/claimant.rb
class Claimant < ApplicationRecord
  include WcaAddressable

end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :business_company
end

app/models/employee.rb
class Employee < User

  # after_initialize :init



  # def init
  #   self.user_types << 'Employee'
  # end













end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true, optional: true

  validates_size_of :image, maximum: 4.megabytes, message: "size should be less than 4MB"

  mount_uploader :image, ImageUploader
  process_in_background :image

end

app/models/injury_type.rb
class InjuryType < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

app/models/medical_clinic.rb
class MedicalClinic < ApplicationRecord
  belongs_to :business_company

end

app/models/payment_profile.rb
class PaymentProfile < ApplicationRecord
  attr_accessor :card_cvc
  belongs_to :business_company
  validates :card_name, :card_number, :card_expiry_date, :token, presence: true
end

app/models/role.rb
class Role < ApplicationRecord

  has_and_belongs_to_many :users, join_table: :users_roles
  belongs_to :resource, polymorphic: true, optional: true
  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true
  scopify

end

app/models/task.rb
class Task < ApplicationRecord

  # validates :description, presence: true
  # validates :task_date, timeliness: { type: :date }
  # validates :completion_date, timeliness: { type: :date }, allow_nil: true
  has_many :bc_tasks
  scope :pending_task, -> { where("is_pending = ? AND task_date <= ?", true, Date.today) }
  scope :order_by_task_date, -> {order("completion_date DESC, task_date ASC, created_at DESC")}


end

app/models/user.rb
class User < ApplicationRecord
  rolify
  attr_accessor :terms_of_service, :name, :current_password
  include WcaAddressable
  include Imagable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true, length: {maximum: 110}
  validates :email, presence: true, length: {maximum: 200}, format: { with: Devise.email_regexp }
  validates_uniqueness_of :email, message: " is already registered with us. Please try reseting your password."
  validates :phone, presence: true, length: {maximum: 18}, format: { with: /\A[+]{0,1}[\s\/\(\)\-\.\d]{10,15}\z/ }

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def full_name
    "#{first_name.camelize}#{" "+last_name.camelize if last_name.present?}"
  end

  def role_type
    if self.roles.present?
      self.roles.first.name
    else
      self.type
    end
  end

  def is_owner?
    has_role? :owner
  end

  def lock!
    update_columns(locked: true)
  end

  def unlock!
    update_columns(locked: false)
  end

end

app/controllers/business_companies_controller.rb
class BusinessCompaniesController < ApplicationController
  layout "dashboard"
  before_action :handle_response, only: [:update]
  before_action :initialize_business_companies, :initialize_business_company

  def show
  end

  def update
    if @business_company.update_attributes(business_company_params)
      flash[:notice] = "Client has been updated successfully."
    else
      flash[:error] = @business_company.errors.full_messages.join("<br/>")
    end
  end

  def preferences
  end

  private

  def initialize_business_company
    @business_company = @business_companies.where(id: params[:id]).first if @business_companies.present?
    if @business_company.blank?
      flash[:error] = "client is not found."
      redirect_to dashboard_path
    end
  end

  def handle_response
    respond_to do |format|
      format.html{ redirect_to dashboard_path }
      format.js{ }
    end
  end

  def business_company_params
    params.require(:business_company).permit(:name, :phone, :policy_number, :policy_year, :medical_clinic, :insurance_company, :notepad, :broker_of_record, :who_to_bill, :payment_options, payment_profiles_attributes:[:card_name, :card_number, :card_expiry_date, :token], address_attributes: [:address, :city, :state, :country, :zip], bc_tasks_attributes: [:task_id, :id, :active])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  include HtmlSolutionHelper

end

app/views/business_companies/_claimant_table.html.erb
<!-- BEGIN EXAMPLE TABLE PORTLET-->
<div class="portlet light bordered">
  <div class="portlet-title">
    <div class="caption font-dark">
      <i class="icon-settings font-dark"></i>
      <span class="caption-subject bold uppercase"> Managed Table</span>
    </div>
    <div class="actions">
      <div class="btn-group btn-group-devided" data-toggle="buttons">
        <label class="btn btn-transparent dark btn-outline btn-circle btn-sm active">
          <input type="radio" name="options" class="toggle" id="option1">Actions
        </label>
        <label class="btn btn-transparent dark btn-outline btn-circle btn-sm">
          <input type="radio" name="options" class="toggle" id="option2">Settings
        </label>
      </div>
    </div>
  </div>
  <div class="portlet-body">
    <div class="table-toolbar">
      <div class="row">
        <div class="col-md-6">
          <div class="btn-group">
            <a href="<%= new_client_business_company_claimant_path(@business_company.client.id, @business_company.id) %>" data-remote='true' class="btn sbold green" >Add New<i class="fa fa-plus"></i></a>
          </div>
        </div>
        <div class="col-md-6">
          <div class="btn-group pull-right">
            <button class="btn green  btn-outline dropdown-toggle" data-toggle="dropdown">Tools
              <i class="fa fa-angle-down"></i>
            </button>
            <ul class="dropdown-menu pull-right">
              <li>
                <a href="javascript:;">
                  <i class="fa fa-print"></i> Print
                </a>
              </li>
              <li>
                <a href="javascript:;">
                  <i class="fa fa-file-pdf-o"></i> Save as PDF
                </a>
              </li>
              <li>
                <a href="javascript:;">
                  <i class="fa fa-file-excel-o"></i> Export to Excel
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <table class="table table-striped table-bordered table-hover table-checkable order-column" id="sample_1">
      <thead>
        <tr>
          <th>
            <input type="checkbox" class="group-checkable" data-set="#sample_1 .checkboxes" />
          </th>
          <th> Claimant Name </th>
          <th> Claimant Phone </th>
          <th> Tasks (Number) </th>
          <th> Status </th>
          <th> Joined </th>
        </tr>
      </thead>
      <tbody>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">shuxer</a> </td>
          <td>123 456 7890</td>
          <td>10</td>
          <td>
            <span class="label label-sm label-success"> Approved </span>
          </td>
          <td class="center"> 12 Jan 2012 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">looper</a> </td>
          <td>123 456 7890</td>
          <td>32</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">userwow</a></td>
          <td>123 456 7890</td>
          <td>56</td>
          <td>
            <span class="label label-sm label-success"> Approved </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">user1wow</a></td>
          <td>123 456 7890</td>
          <td>15</td>
          <td>
            <span class="label label-sm label-danger"> Blocked </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">restest</a></td>
          <td>123 456 7890</td>
          <td>6</td>
          <td>
            <span class="label label-sm label-success"> Approved </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">foopl</a></td>
          <td>123 456 7890</td>
          <td>167</td>
          <td>
            <span class="label label-sm label-info"> Info </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">weep</a></td>
          <td>123 456 7890</td>
          <td>23</td>
          <td>
            <span class="label label-sm label-danger"> Rejected </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">coop</a></td>
          <td>123 456 7890</td>
          <td>43</td>
          <td>
            <span class="label label-sm label-info"> Info </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">pppol</a></td>
          <td>123 456 7890</td>
          <td>55</td>
          <td>
            <span class="label label-sm label-danger"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">test</a></td>
          <td>123 456 7890</td>
          <td>11</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">userwow</a></td>
          <td>123 456 7890</td>
          <td>4</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">testTom</a></td>
          <td>123 456 7890</td>
          <td>12</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">goop</a></td>
          <td>123 456 7890</td>
          <td>22</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">weep</a></td>
          <td>123 456 7890</td>
          <td>45</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">toopl</a></td>
          <td>123 456 7890</td>
          <td>33</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">userwow</a></td>
          <td>123 456 7890</td>
          <td>52</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">tes21t</a></td>
          <td>123 456 7890</td>
          <td>65</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">fop</a></td>
          <td>123 456 7890</td>
          <td>28</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
        <tr class="odd gradeX">
          <td>
            <input type="checkbox" class="checkboxes" value="1" />
          </td>
          <td><a href="BC-injury-profile.html">weep</a></td>
          <td>123 456 7890</td>
          <td>39</td>
          <td>
            <span class="label label-sm label-warning"> Suspended </span>
          </td>
          <td class="center"> 12.12.2011 </td>
        </tr>
      </tbody>
    </table>
  </div>
</div><!-- magage-table -->
<!-- END EXAMPLE TABLE PORTLET -->

app/views/business_companies/_company_account.html.erb
<div id="company-account" class="bctab-content">
  <div class="profile-content">
    <div class="row">
      <div class="col-md-12">
        <div class="portlet light ">
          <div class="portlet-title tabbable-line">
            <div class="caption caption-md">
              <i class="icon-globe theme-font hide"></i>
              <span class="caption-subject font-blue-madison bold uppercase">Profile Account</span>
            </div>
            <!-- Nav tabs -->
            <ul class="nav nav-tabs" role="tablist">
              <li role="presentation" class="active"><a href="#company_info" aria-controls="info" role="tab" data-toggle="tab">Company Info</a></li>

              <!-- <li role="presentation"><a href="#policy" aria-controls="policy" role="tab" data-toggle="tab">Insurance Policy</a></li> -->
              <li role="presentation"><a href="#change_password" aria-controls="password" role="tab" data-toggle="tab">Client Info</a></li>

              <li role="presentation"><a href="#settings" aria-controls="settings" role="tab" data-toggle="tab">Task Settings</a></li>
            </ul>
          </div><!-- portlet-title -->

          <div class="portlet-body">
            <!-- Tab panes -->
            <div class="tab-content">

              <!-- PERSONAL INFO TAB -->
              <div role="tabpanel" class="tab-pane active" id="company_info">
                <%= nested_form_for @business_company, url: client_business_company_path(@business_company.client.id, @business_company.id), method: "put", remote: true, html:{ class: 'company_form', id: 'company_info_form' } do |f| %>
                  <div class="form-group">
                    <label class="control-label">Company Name</label><span class="required"> * </span>
                    <%=  f.text_field :name, class: 'form-control', placeholder: 'Company Name' %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">Company Phone</label><span class="required"> * </span>
                    <%=  f.text_field :phone, class: 'form-control', placeholder: 'Company Phone' %>
                  </div>

                  <%= f.fields_for :address do |ff| %>

                    <div class="form-group">
                      <label class="control-label">Company Address
                        <span class="required"> * </span>
                      </label>
                        <%= ff.text_field :address, class: "form-control" %>
                    </div>

                    <div class="form-group">
                      <label class="control-label">Company City/Town
                        <span class="required"> * </span>
                      </label>
                        <%= ff.text_field :city, class: "form-control" %>
                    </div>

                    <div class="form-group">
                      <label class="control-label">Company State
                        <span class="required"> * </span>
                      </label>
                        <%= ff.text_field :state, class: "form-control" %>
                    </div>

                    <div class="form-group">
                      <label class="control-label">Company Zip
                        <span class="required"> * </span>
                      </label>
                        <%= ff.text_field :zip, class: "form-control" %>
                    </div>

                    <div class="form-group">
                      <label class="control-label">Company Country</label>
                        <%= ff.country_select(:country,{ selected: @business_company.country.present? ? @business_company.country : "US", prompt: 'Please select..' }, { class: "form-control", required: true }) %>
                    </div>
                  <% end %>

                  <div class="form-group">
                    <label class="control-label">Notepad</label>
                    <%=  f.text_area :notepad, class: 'form-control', placeholder: 'Message' %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">Broker of record</label>
                    <input type="text" placeholder="Record" class="form-control" />
                  </div>


                  <div class="form-group">
                    <label class="control-label">Who to Bill?</label>
                      <%= f.select :who_to_bill, options_for_select(BusinessCompany::WHO_TO_BILL, f.object.who_to_bill), {}, class: "form-control" %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">Dedicated Email</label>
                    <input type="email" placeholder="demo@gmail.com" class="form-control" />
                  </div>

                  <div class="margiv-top-10">
                    <%= f.submit "Save Changes", class: "btn green" %>
                    <a href="javascript:void(0)" class="form_cancel_btn btn default"> Cancel </a>
                  </div>
                <% end %>
              </div>
              <!-- END PERSONAL INFO TAB -->

              <!-- INSURANCE POLICY TAB -->
              <div role="tabpanel" class="tab-pane" id="policy">
                <form role="form" action="#">
                  <div class="form-group">
                    <div class="template">
                      <div class="form-group">
                        <label class="control-label">Policy Number</label>
                        <input type="text" placeholder="Policy Number" class="form-control" />
                      </div>
                      <div class="form-group">
                        <label class="control-label" for="field1">Policy Year</label>
                        <input class="year-input form-control input-medium" type="number" min="1880" max="2222" placeholder="YYYY">
                      </div>
                      <div class="input-group stylish-input-group">
                        <input type="text" class="form-control"  placeholder="Insurance Company search ..." >
                        <span class="input-group-addon">
                          <button type="submit">
                            <span class="glyphicon glyphicon-search"></span>
                          </button>
                        </span>
                      </div>
                    </div>
                    <input type="button" id="add_more" value="+" class="btn btn-icon-only green" />
                  </div>
                </form>
              </div>
              <!-- END INSURANCE POLICY TAB -->


              <!-- CHANGE PASSWORD TAB -->
              <div role="tabpanel" class="tab-pane" id="change_password">
                <%= nested_form_for @business_company.client, url: client_path(@business_company.client.id, business_company_id: @business_company.id ), method: "put", remote: true, html:{ class: 'company_form', id: 'client_edit_form' } do |f| %>

                  <div class="form-group">
                    <label class="control-label">First Name</label>
                    <%=  f.text_field :first_name, class: 'form-control', placeholder: 'First Name' %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">Last Name</label>
                    <%=  f.text_field :last_name, class: 'form-control', placeholder: 'Last Name' %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">Phone Number</label>
                    <%=  f.text_field :phone, class: 'form-control', placeholder: 'Phone Number' %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">New Password</label>
                    <%=  f.password_field :password, class: 'form-control', placeholder: 'New Password' %>
                  </div>

                  <div class="form-group">
                    <label class="control-label">Re-type New Password</label>
                    <%=  f.password_field :password_confirmation, class: 'form-control', placeholder: 'Re-type New Password' %>
                  </div>

                  <div class="margin-top-10">
                    <%=  f.submit "Save Changes", class: 'btn green' %>
                    <a href="javascript:void(0)" class="form_cancel_btn btn default"> Cancel </a>
                  </div>
                <% end %>
              </div>
              <!-- END CHANGE PASSWORD TAB -->

              <!-- TASK SETTINGS TAB -->
              <div role="tabpanel" class="tab-pane" id="settings">
                <%= nested_form_for @business_company, url: client_business_company_path(@business_company.client.id, @business_company.id), method: "put", remote: true, html:{ class: 'company_form', id: 'company_task_form' } do |f| %>
                  <table class="table table-light table-hover">
                    <%= f.fields_for :bc_tasks, @business_company.bc_tasks.sort_by(&:created_at) do |ff|%>
                      <tr>
                        <td><%= ff.object.name %></td>
                        <td>
                          <label class="uniform-inline">
                            <%= ff.check_box :active %> Yes
                          </label>
                        </td>
                      </tr>
                    <% end %>
                  </table>
                  <div class="margin-top-10">
                    <%= f.submit "Save Changes", class: 'btn red' %>
                    <a href="javascript:void(0)" class="form_cancel_btn btn default"> Cancel </a>
                  </div>
                <% end %>
              </div>
              <!-- END PRIVACY SETTINGS TAB -->

            </div>
          </div><!-- portlet-body -->
        </div><!-- portlet -->
      </div>
    </div>
  </div><!-- profile-content -->
</div><!-- company-account -->
<script>
  $(document).ready(function(){

    $('#add_more').click(function () {
      $(this).before($(".template").clone());
    });

    $('.tab-menu li').click(function(){
      var tab_id = $(this).attr('data-tab');
      $('.tab-menu li').removeClass('active');
      $('.bctab-content').removeClass('active');
      $(this).addClass('active');
      $("#"+tab_id).addClass('active');
    })

    validate_business_company($('#company_info_form'));
    validate_business_client($('#client_edit_form'));
  });
</script>

app/views/business_companies/_company_information.html.erb
<div class="profile-usermenu" id="company_information">
  <ul class="nav">
    <li class="active">
      <strong> Company Information </strong>
    </li>
    <li><%= @business_company.name.camelize %></li>
    <li><%= @business_company.full_address.camelize %></li>
    <li><%= @business_company.phone %></li>
    <li><%= @business_company.contact_person_name.camelize %></li>
    <li><%= @business_company.contact_person_email.camelize %></li>
  </ul>
</div>

app/views/business_companies/_preferences.html.erb
<div class="page-content-wrapper">
  <div class="page-content">
    <div class="todo-main-header">
      <h3>Preferences</h3>
      <ul class="todo-breadcrumb">
        <li>
          <a href="<%=  %>">Business Company</a>
        </li>
        <li>
          <a class="todo-active" href="#">Preferences</a>
        </li>
      </ul>
    </div>

    <div class="flash_message">
      <%= render partial: "shared/flash_message" %>
    </div>

    <div class="todo-container">
      <div class="row">
        <div class="col-md-12">
          <ul class="todo-projects-container">
            <li class="todo-padding-b-0">
              <select class="form-control" id="preferences_select">
                <option selected disabled="disabled">Select Preference Type</option>
                <option value="<%= client_business_company_bc_branches_path(@business_company.client.id, @business_company.id) %>">Branch </option>
                <option value="<%= client_business_company_bc_departments_path(@business_company.client.id, @business_company.id) %>">Department</option>
                <option value="<%= client_business_company_bc_medical_clinics_path(@business_company.client.id, @business_company.id) %>">Medical Clinic</option>
              </select>
            </li>
          </ul>
        </div>
      </div>
    </div>

    <div class="todo-container">
      <div class="row">
        <div class="col-md-12">
          <ul class="todo-projects-container" id="preferences_index">
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/business_companies/preferences.html.erb
<% content_for :title do %>
  <%= APP_CONFIG['project_name'] %> | Business Company Preferences
<% end %>

<%= render partial: 'preferences' %>

app/views/business_companies/preferences.js.erb
$('.render_class').html("<%= j(render partial: 'preferences') %>");
$('title').text("<%= APP_CONFIG['project_name'] %> | Business Company Preferences");
$(window).scrollTop(0);