config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get 'lock_user', to: 'users/sessions#lock_user'
    post 'unlock_user', to: 'users/sessions#unlock_user'
  end

  resources :business_clients, except: [:show, :destroy, :edit], path: 'clients', as: 'clients' do

    get :autocomplete, on: :collection

    resources :business_companies, path: 'companies', only:[:show, :update] do

      get :preferences, on: :member

      namespace 'bc' do
        resources :departments
        resources :branches
        resources :medical_clinics
      end

      resources :dashboard, only: [:index]
      resources :claimants
    end
  end

  root to: 'home#index'
  get 'dashboard', to: 'users/dashboard#index', as: :dashboard
  get '*unmatched_route', :to => 'home#routing_error'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.has_role? :owner
      can :manage, :all
    elsif user.has_role? :client
      cannot :manage, [:business_clients]
      can [:update], BusinessClient, id: user.id
    end
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :addressable, polymorphic: true, optional: true

  validates :address, presence: true, length: {maximum: 255}
  validates :city, :state, presence: true, length: {maximum: 50}
  validates :zip, allow_blank: true, length: {maximum: 15}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  scope :created_at_desc, -> { order('created_at DESC') }
  scope :created_at_asc, -> { order('created_at ASC') }
end

app/models/bc_task.rb
class BcTask < ApplicationRecord
  belongs_to :business_company
  belongs_to :task

  #before_save :custom_validation

  def name
    task.name
  end
end

app/models/body_part.rb
class BodyPart < ApplicationRecord
  scope :order_by_name, -> { order("name") }
end

app/models/branch.rb
class Branch < ApplicationRecord

  belongs_to :business_company
  # has_many :employees
  # has_many :medical_clinics

end

app/models/business_client.rb
class BusinessClient < User
  attr_accessor :name
  has_many :business_companies
  accepts_nested_attributes_for :business_companies

end

app/models/business_company.rb
class BusinessCompany < ApplicationRecord

  belongs_to :business_client
  has_many :employees
  has_many :branches
  has_many :departments
  has_many :medical_clinics
  has_many :bc_tasks
  has_many :payment_profiles, dependent: :destroy

  validates :name, presence: true, length: {maximum: 110}
  validates :phone, presence: true, length: {maximum: 18}, format: { with: /\A[+]{0,1}[\s\/\(\)\-\.\d]{10,15}\z/ }

  accepts_nested_attributes_for :branches, allow_destroy: true
  accepts_nested_attributes_for :departments, allow_destroy: true
  accepts_nested_attributes_for :payment_profiles, allow_destroy: true
  accepts_nested_attributes_for :bc_tasks, allow_destroy: true

  after_create :build_tasks

  include DateTimeParser
  include WcaAddressable

  scope :search_by_name, -> (keyword){ where("lower(name) like ? ", "%#{keyword.downcase}%") }

  WHO_TO_BILL = { 'Company': 1, 'Broker': 2, 'Insurance Company': 3 }
  PAYMENT_OPTIONS = { 'Auto-Pay with this Credit Card': 1, 'Email me monthly billing': 2 }

  def client
    business_client
  end

  def contact_person_email
    client.email
  end

  def contact_person_phone
    client.phone
  end

  def contact_person_name
    client.full_name
  end

  private

  def build_tasks
    Task.all.each{ |task| self.bc_tasks.create(task_id: task.id) }
  end

end

app/models/claimant.rb
class Claimant < ApplicationRecord
  include WcaAddressable

end

app/models/department.rb
class Department < ApplicationRecord
  belongs_to :business_company
end

app/models/employee.rb
class Employee < User

  # after_initialize :init



  # def init
  #   self.user_types << 'Employee'
  # end













end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true, optional: true

  validates_size_of :image, maximum: 4.megabytes, message: "size should be less than 4MB"

  mount_uploader :image, ImageUploader
  process_in_background :image

end

app/models/injury_type.rb
class InjuryType < ApplicationRecord
end

app/models/invoice.rb
class Invoice < ApplicationRecord
end

app/models/invoice_detail.rb
class InvoiceDetail < ApplicationRecord
end

app/models/medical_clinic.rb
class MedicalClinic < ApplicationRecord
  belongs_to :business_company

end

app/models/payment_profile.rb
class PaymentProfile < ApplicationRecord
  attr_accessor :card_cvc
  belongs_to :business_company
  validates :card_name, :card_number, :card_expiry_date, :token, presence: true
end

app/models/role.rb
class Role < ApplicationRecord

  has_and_belongs_to_many :users, join_table: :users_roles
  belongs_to :resource, polymorphic: true, optional: true
  validates :resource_type, inclusion: { in: Rolify.resource_types }, allow_nil: true
  scopify

end

app/models/task.rb
class Task < ApplicationRecord

  # validates :description, presence: true
  # validates :task_date, timeliness: { type: :date }
  # validates :completion_date, timeliness: { type: :date }, allow_nil: true
  has_many :bc_tasks
  scope :pending_task, -> { where("is_pending = ? AND task_date <= ?", true, Date.today) }
  scope :order_by_task_date, -> {order("completion_date DESC, task_date ASC, created_at DESC")}


end

app/models/user.rb
class User < ApplicationRecord
  rolify
  attr_accessor :terms_of_service, :name, :current_password
  include WcaAddressable
  include Imagable
  devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable

  validates :first_name, presence: true, length: {maximum: 110}
  validates :email, presence: true, length: {maximum: 200}, format: { with: Devise.email_regexp }
  validates_uniqueness_of :email, message: " is already registered with us. Please try reseting your password."
  validates :phone, presence: true, length: {maximum: 18}, format: { with: /\A[+]{0,1}[\s\/\(\)\-\.\d]{10,15}\z/ }

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  def full_name
    "#{first_name.camelize}#{" "+last_name.camelize if last_name.present?}"
  end

  def role_type
    if self.roles.present?
      self.roles.first.name
    else
      self.type
    end
  end

  def is_owner?
    has_role? :owner
  end

  def lock!
    update_columns(locked: true)
  end

  def unlock!
    update_columns(locked: false)
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <link rel="icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <link rel="icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "dashboard", media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag "dashboard", 'data-turbolinks-track': true %>
  </head>
  <body class="page-header-fixed page-sidebar-closed-hide-logo page-container-bg-solid page-content-white <%= "page-sidebar-closed" if is_sidebar_closed? %>">

    <div id="header_section">
      <%= render partial: 'shared/header' %>
    </div>

    <div class="clearfix"></div>
    <div class="page-container">
      <div class="left_sidebar">
        <%= render partial: 'shared/left_sidebar' %>
      </div>
      <div class="render_class">
        <%= yield %>
      </div>

      <%= render partial: 'shared/right_sidebar' %>
      <div class="pop_up">
    </div>
    <%= render partial: 'shared/footer' %>
  </body>
</html>

app/views/layouts/lock_user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= APP_CONFIG['project_name'] %> | User Locked</title>
    <link rel="icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'registration', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'registration', 'data-turbolinks-track': true %>
    <%= stylesheet_link_tag 'lock.min' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/registration.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <link rel="icon" href="/favicon.ico">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag 'registration', media: 'all', 'data-turbolinks-track': true %>
    <%= javascript_include_tag 'registration', 'data-turbolinks-track': true %>
  </head>
  <body class="login">
    <div class="logo"><a href="/"><img src="/assets/logo-big.png" alt="" /></a></div>
    <%= yield %>
    <div class="copyright"> <%= Time.now.year %> © <%= APP_CONFIG['project_name'] %> </div>
  </body>
</html>

app/views/shared/_add_preferences_popup.html.erb
<div class="modal fade" id="add-prefences-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><%= title %></h4>
      </div>
      <%= render page %>
    </div>
  </div>
</div>

app/views/shared/_flash_message.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert_margin alert <%= get_alert_class(name) %>" >
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.html_safe, id: "flash_#{name}" %>
    </div>
  <% end %>

  <% if msg.is_a?(Array) %>
    <div class="alert_margin alert <%= get_alert_class(name) %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg.first.html_safe, id: "flash_#{name}" %>
    </div>
  <% end %>
  <% flash.discard(name) %>
<% end %>

<script>
  hide_success_flash_message();
  flash_popup();
  function hide_success_flash_message(){
    $(".alert-success" ).delay(7000).fadeOut('slow')
  }

  function flash_popup(){
    if (<%= flash[:notice].present? || flash[:success].present? %>)
      iziToast.success({ position: 'topRight', color: '#a7eef5', message: "<%= flash[:notice] || flash[:success] %>" });
    if (<%= flash[:error].present? %>)
      iziToast.error({ position: 'topRight', message: '<%= flash[:error].html_safe if flash[:error] %>'});
    if (<%= flash[:alert].present? %>)
      iziToast.error({ position: 'topRight', message: '<%= flash[:alert].html_safe if flash[:alert] %>'});
    <% flash.discard %>
  }

</script>

app/views/shared/_footer.html.erb
<!-- BEGIN FOOTER -->
<div class="page-footer">
  <div class="page-footer-inner"> 2014 &copy; Metronic by keenthemes.
    <a href="http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes" title="Purchase Metronic just for 27$ and get lifetime updates for free" target="_blank">Purchase Metronic!</a>
  </div>
  <div class="scroll-to-top">
    <i class="icon-arrow-up"></i>
  </div>
</div>
<!-- END FOOTER -->

app/views/shared/_header.html.erb
<!-- BEGIN HEADER -->
<div class="page-header navbar navbar-fixed-top">
  <!-- BEGIN HEADER INNER -->
  <div class="page-header-inner ">

    <!-- BEGIN LOGO -->
    <div class="page-logo">
      <a href="<%= dashboard_path %>" data-remote='true' ><img src="/assets/logo.png" alt="logo" class="logo-default" /></a>
      <div class="menu-toggler sidebar-toggler"> </div>
    </div>
    <!-- END LOGO -->

    <!-- BEGIN RESPONSIVE MENU TOGGLER -->
    <a href="javascript:void(0)" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse"></a>
    <!-- END RESPONSIVE MENU TOGGLER -->

    <!-- BEGIN TOP NAVIGATION MENU -->
    <div class="top-menu">
      <ul class="nav navbar-nav pull-right">

        <!-- BEGIN USER LOGIN DROPDOWN -->
        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
        <li class="dropdown dropdown-user">
          <a href="javascript:void(0)" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
            <span class='abc'>
              <% if @current_user.image.present? && @current_user.image.persisted? %>
                <%= image_tag @image || @current_user.avatar %>
              <% else %>
                <img class="img-circle" src="/assets/no-image.png" alt="">
              <% end %>
            </span>
            <span class="username username-hide-on-mobile"> <%= current_user.full_name %></span>
            <i class="fa fa-angle-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-menu-default">
            <li>
              <a href="<%= edit_user_registration_path %>"><i class="icon-user"></i>My Profile</a>
            </li>
            <li class="divider"></li>
            <li>
              <a href="<%= lock_user_path %>"><i class="icon-lock"></i> Lock Screen </a>
            </li>
            <li>
              <a href="<%= destroy_user_session_path %>" data-method="delete"><i class="icon-key"></i> Log Out</a>
            </li>
          </ul>
        </li>
        <!-- END USER LOGIN DROPDOWN -->
        <!-- BEGIN QUICK SIDEBAR TOGGLER -->
        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
        <li class="dropdown dropdown-quick-sidebar-toggler">
          <a href="javascript:void(0)" class="dropdown-toggle">
            <i class="icon-logout"></i>
          </a>
        </li>
        <!-- END QUICK SIDEBAR TOGGLER -->
      </ul>
    </div>
    <!-- END TOP NAVIGATION MENU -->

  </div>
  <!-- END HEADER INNER -->
</div>
<!-- END HEADER -->

app/views/shared/_left_sidebar.html.erb
<!-- BEGIN SIDEBAR -->
<div class="page-sidebar-wrapper">
  <!-- BEGIN SIDEBAR -->
  <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
  <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
  <div class="page-sidebar navbar-collapse collapse">
    <!-- BEGIN SIDEBAR MENU -->
    <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
    <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
    <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
    <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
    <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
    <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
    <ul class="page-sidebar-menu  page-header-fixed <%= "page-sidebar-menu-closed" if is_sidebar_closed? %>" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200" style="padding-top: 20px">
      <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
      <li class="sidebar-toggler-wrapper hide">
        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
        <div class="sidebar-toggler"> </div>
        <!-- END SIDEBAR TOGGLER BUTTON -->
      </li>
      <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
      <li class="sidebar-search-wrapper">
        <!-- BEGIN RESPONSIVE QUICK SEARCH FORM -->
        <!-- DOC: Apply "sidebar-search-bordered" class the below search form to have bordered search box -->
        <!-- DOC: Apply "sidebar-search-bordered sidebar-search-solid" class the below search form to have bordered & solid search box -->
        <form class="sidebar-search  " action="page_general_search_3.html" method="POST">
          <a href="javascript:;" class="remove">
            <i class="icon-close"></i>
          </a>
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Search...">
            <span class="input-group-btn">
              <a href="javascript:;" class="btn submit">
                <i class="icon-magnifier"></i>
              </a>
            </span>
          </div>
        </form>
        <!-- END RESPONSIVE QUICK SEARCH FORM -->
      </li>
      <li class="nav-item start active open">
        <a href="javascript:;" class="nav-link nav-toggle">
          <i class="icon-home"></i>
          <span class="title">WCA Portal</span>
          <span class="selected"></span>
          <span class="arrow open"></span>
        </a>
        <ul class="sub-menu">

          <li class="nav-item start active open">
            <a href="/dashboard" data-remote='true' class="nav-link ">
              <i class="icon-clock"></i>
              <span class="title">Task Manager</span>
              <span class="badge badge-success"></span>
            </a>
          </li>

          <% if current_user.is_owner? && is_dashboard? %>
            <li class="nav-item start">
              <a href="<%= clients_path %>" data-remote='true' class="nav-link ">
                <i class="icon-heart"></i>
                <span class="title">All Clients</span>
                <span class="selected"></span>
              </a>
            </li>

            <li class="nav-item start ">
              <a href="<%= new_client_path %>" data-remote="true" class="nav-link ">
                <i class="icon-plus"></i>
                <span class="title">Add a New Clients</span>
                <span class="selected"></span>
              </a>
            </li>

            <li class="nav-item start ">
              <a href="page_general_invoice_2.html" class="nav-link ">
                <i class="icon-credit-card"></i>
                <span class="title">Invoices</span>
                <span class="badge badge-danger"></span>
              </a>
            </li>
          <% end %>

          <% if @business_company.present? %>
            <li class="nav-item start ">
              <a href="<%= preferences_client_business_company_path(@business_company.client.id, @business_company.id) %>" class="nav-link ">
                <i class="icon-settings"></i>
                <span class="title">Company Preferences</span>
                <span class="badge badge-danger"></span>
              </a>
            </li>
          <% end %>

        </ul>
      </li>
    </ul>
  </div>
  <!-- END SIDEBAR -->
</div>
<!-- END SIDEBAR -->

app/views/shared/_no_data.html.erb
<div class="no-data">You have no <%= type %><br>
  <span>When you have <%= type %> we will list them here</span>
</div>