config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web, at: '/sidekiq'

  devise_for :users, controllers: {
    registrations: "users/registrations",
    confirmations: "users/confirmations",
    sessions: "users/sessions",
    passwords: "users/passwords"
  }

  devise_scope :user do
    get 'lock_user', to: 'users/sessions#lock_user'
    post 'unlock_user', to: 'users/sessions#unlock_user'
  end

  resources :business_clients, except: [:show, :destroy, :edit], path: 'clients', as: 'clients' do

    get :autocomplete, on: :collection

    resources :business_companies, path: 'companies', only:[:show, :update] do

      get :preferences, on: :member

      namespace 'bc' do
        resources :departments
        resources :branches
        resources :medical_clinics
      end

      resources :dashboard, only: [:index]
      resources :claimants
    end
  end

  root to: 'home#index'
  get 'dashboard', to: 'users/dashboard#index', as: :dashboard
  get '*unmatched_route', :to => 'home#routing_error'

end

app/models/branch.rb
class Branch < ApplicationRecord

  belongs_to :business_company
  # has_many :employees
  # has_many :medical_clinics

end

app/controllers/bc/base_controller.rb
class Bc::BaseController < ApplicationController
  before_action :handle_response, :initialize_business_client_and_company

  ['branches', 'departments', 'medical_clinics'].each do |name|
    define_method "init_#{name}" do
      instance_variable_set("@#{name}", eval("@business_company.#{name}.created_at_desc"))
    end
  end

  private

  def handle_response
    respond_to do |format|
      format.html{ redirect_to dashboard_path }
      format.js{ }
    end
  end

  def initialize_business_client_and_company
    @business_client = BusinessClient.where(id: params[:client_id]).first
    @business_company = @business_client.business_companies.where(id: params[:business_company_id]).first if @business_client.present?
    if @business_client.blank? && @business_company.blank?
      flash[:error] = "Client is not found."
      redirect_to dashboard_path
    end
  end

end

app/controllers/bc/branches_controller.rb
class Bc::BranchesController < Bc::BaseController
  before_action :initialize_branch, only: [:edit, :update, :destroy]

  def index
    init_branches
  end

  def new
    @branch = @business_company.branches.new
  end

  def edit
  end

  def create
    @branch = @business_company.branches.new(branch_params)
    if @branch.save
      flash[:notice] = "Branch has been created successfully."
    else
      flash[:error] = @branch.errors.full_messages.join("<br/>").html_safe
    end
    init_branches
  end

  def update
    if @branch.update_attributes(branch_params)
      flash[:notice] = "Branch has been updated successfully."
    else
      flash[:error] = @branch.errors.full_messages.join("<br/>").html_safe
    end
    init_branches
  end

  def destroy
    if @branch.destroy && @branch.destroyed?
      flash[:notice] = "Branch has been deleted successfully."
    else
      flash[:error] = @branch.errors.full_messages.join("<br/>").html_safe
    end
    init_branches
  end

  private

  def initialize_branch
    @branch = @business_company.branches.where(id: params[:id]).first
    flash[:error] = "Branch is not found." if @branch.blank?
  end

  def branch_params
    params.require(:branch).permit(:name)
  end

end

app/controllers/bc/departments_controller.rb
class Bc::DepartmentsController < Bc::BaseController
  before_action :initialize_department, only: [:edit, :update, :destroy]

  def index
    init_departments
  end

  def new
    @department = @business_company.departments.new
  end

  def edit
  end

  def create
    @department = @business_company.departments.new(department_params)
    if @department.save
      flash[:notice] = "Department has been created successfully."
    else
      flash[:error] = @department.errors.full_messages.join("<br/>").html_safe
    end
    init_departments
  end

  def update
    if @department.update_attributes(department_params)
      flash[:notice] = "Department has been updated successfully."
    else
      flash[:error] = @department.errors.full_messages.join("<br/>").html_safe
    end
    init_departments
  end

  def destroy
    if @department.destroy && @department.destroyed?
      flash[:notice] = "Department has been deleted successfully."
    else
      flash[:error] = @department.errors.full_messages.join("<br/>").html_safe
    end
    init_departments
  end

  private

  def initialize_department
    @department = @business_company.departments.where(id: params[:id]).first
    flash[:error] = "Department is not found." if @department.blank?
  end

  def department_params
    params.require(:department).permit(:name)
  end

end

app/controllers/bc/medical_clinics_controller.rb
class Bc::MedicalClinicsController < Bc::BaseController
  before_action :initialize_medical_clinic, only: [:edit, :update, :destroy]

  def index
    init_medical_clinics
  end

  def new
    @medical_clinic = @business_company.medical_clinics.new
  end

  def edit
  end

  def create
    @medical_clinic = @business_company.medical_clinics.new(medical_clinic_params)
    if @medical_clinic.save
      flash[:notice] = "Medical clinic has been created successfully."
    else
      flash[:error] = @medical_clinic.errors.full_messages.join("<br/>").html_safe
    end
    init_medical_clinics
  end

  def update
    if @medical_clinic.update_attributes(medical_clinic_params)
      flash[:notice] = "Medical clinic has been updated successfully."
    else
      flash[:error] = @medical_clinic.errors.full_messages.join("<br/>").html_safe
    end
    init_medical_clinics
  end

  def destroy
    if @medical_clinic.destroy && @medical_clinic.destroyed?
      flash[:notice] = "Medical clinic has been deleted successfully."
    else
      flash[:error] = @medical_clinic.errors.full_messages.join("<br/>").html_safe
    end
    init_medical_clinics
  end

  private

  def initialize_medical_clinic
    @medical_clinic = @business_company.medical_clinics.where(id: params[:id]).first
    flash[:error] = "Medical clinic is not found." if @medical_clinic.blank?
  end

  def medical_clinic_params
    params.require(:medical_clinic).permit(:name)
  end

end

app/views/bc/branches/_edit.html.erb
<%= nested_form_for @branch, url: client_business_company_bc_branch_path(@business_company.client.id, @business_company.id, @branch.id), method: "put", remote: true, html:{ } do |f| %>
  <div class="modal-body">
    <div class="flash"></div>
    <div class="form-group">
      <label for="departmentName">Branch Name</label>
      <%= f.text_field :name, required: true, class: 'form-control', placeholder: 'Branch Name' %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Submit", class: 'btn green' %>
  </div>
<% end %>

app/views/bc/branches/_index.html.erb
<li class="todo-padding-b-0">
  <div class="todo-head">
    <a id="add_bc" href="<%= new_client_business_company_bc_branch_path(@business_company.client.id, @business_company.id) %>" data-remote='true' class="btn btn-square btn-sm green todo-bold">Add Branch</a>
    <h3 style="vertical-align: sub;">Branches</h3>
  </div>
</li>

<li class="todo-padding-b-0" id="table_index">
  <% if @branches.present? %>
    <table class="table">
      <thead>
        <th>Name</th>
        <th>Edit</th>
        <th>Delete</th>
      </thead>

      <tbody>
        <% @branches.each do |branch| %>
          <tr id="<%= branch.id %>">
            <td><%= branch.name.camelize %></td>
            <td>
              <a href="<%= edit_client_business_company_bc_branch_path(@business_company.client.id, @business_company.id, branch.id) %>" data-remote="true" ><i class="icon-pencil"></i></a>
            </td>
            <td>
              <a href="<%= client_business_company_bc_branch_path(@business_company.client.id, @business_company.id, branch.id) %>" data-method="delete" data-remote="true" >
                <i style="color:red;" class="icon-trash"></i>
              </a>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <%= render partial: 'shared/no_data', locals: {type: 'branches'} %>
  <% end %>
</li>

app/views/bc/branches/_new.html.erb
<%= nested_form_for @branch, url: client_business_company_bc_branches_path(@business_company.client.id, @business_company.id), method: "post", remote: true, html:{ } do |f| %>
  <div class="modal-body">
    <div class="flash"></div>
    <div class="form-group">
      <label for="departmentName">Branch Name</label>
      <%= f.text_field :name, required: true, class: 'form-control', placeholder: 'Branch Name' %>
    </div>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <%= f.submit "Submit", class: 'btn green' %>
  </div>
<% end %>

app/views/bc/branches/create.js.erb
<% if flash[:error].blank? %>
  $("#preferences_index").html("<%= j(render 'index') %>");
  $("#add-prefences-modal").modal('hide');
  $(".flash_message").html("<%= j(render 'shared/flash_message') %>");
<% else %>
  $(".flash").html("<%= j(render 'shared/flash_message') %>");
<% end %>
$(window).scrollTop(0);

app/views/bc/branches/destroy.js.erb
<% if flash[:error].blank? %>
  $('tr#<%= @branch.id %>').remove();
  <% unless @branches.present? %>
    $('#table_index').html("<%= j(render partial: 'shared/no_data', locals: { type: 'branches' }) %>");
  <% end %>
<% end %>
$(".flash_message").html("<%= j(render 'shared/flash_message') %>");
$(window).scrollTop(0);

app/views/bc/branches/edit.js.erb
<% if flash[:error].blank? %>
  $('.pop_up').html("<%= j(render partial: 'shared/add_preferences_popup', locals: {page: 'edit', title: 'Edit Branch'}) %>");
  $("#add-prefences-modal").modal('show');
  $('#add-prefences-modal form').validate();
<% else %>
  $(".flash_message").html("<%= j(render 'shared/flash_message') %>");
  $(window).scrollTop(0);
<% end %>

app/views/bc/branches/index.js.erb
$("#preferences_index").html("<%= j(render 'index') %>");

app/views/bc/branches/new.js.erb
$('.pop_up').html("<%= j(render partial: 'shared/add_preferences_popup', locals: {page: 'new', title: 'Add Branch'}) %>");
$("#add-prefences-modal").modal('show');
$('#add-prefences-modal form').validate();

app/views/bc/branches/update.js.erb
<% if flash[:error].blank? %>
  $('tr#<%= @branch.id %>').html('<td><%= @branch.name.camelize %></td> <td> <a href="<%= edit_client_business_company_bc_branch_path(@business_company.client.id, @business_company.id, @branch.id) %>" data-remote="true" ><i class="icon-pencil"></i></a></td><td><a href="<%= client_business_company_bc_branch_path(@business_company.client.id, @business_company.id, @branch.id) %>" data-method="delete" data-remote="true" ><i style="color:red;" class="icon-trash"></i></a></td>');
  $("#add-prefences-modal").modal('hide');
  $(".flash_message").html("<%= j(render 'shared/flash_message') %>");
<% else %>
  $(".flash").html("<%= j(render 'shared/flash_message') %>");
<% end %>
$(window).scrollTop(0);